---
- name: Installer Chocolatey sur Windows
  hosts: windows
  tasks:
    - name: Télécharger et exécuter le script d'installation Chocolatey
      ansible.windows.win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force;
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      register: choco_install

    - name: Vérifier l'installation de Chocolatey
      ansible.windows.win_command: choco --version
      register: choco_version
      changed_when: false

    - name: Afficher la version de Chocolatey
      debug:
        msg: "Chocolatey version installée: {{ choco_version.stdout }}"
