---
- name: Installer Chocolatey sur Windows
  hosts: windows
  vars:
    ansible_user: "{{ lookup('env', 'WIN_USERNAME') }}"
    ansible_password: "{{ lookup('env', 'WIN_PASSWORD') }}"
  tasks:
    - name: Vérifier si Chocolatey est déjà installé
      win_command: choco --version
      register: choco_check
      ignore_errors: true
      changed_when: false

    - name: Vérifier les mises à jour de Chocolatey
      win_command: choco outdated chocolatey
      register: choco_outdated
      when: choco_check.rc == 0
      changed_when: false
      ignore_errors: true

    - name: Télécharger et installer Chocolatey
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force;
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      args:
        executable: powershell.exe
      register: chocolatey_result
      when: choco_check.rc != 0 or choco_outdated.stdout != ''
      changed_when: "'Chocolatey installed' in chocolatey_result.stdout"

    - name: Vérifier l'installation de Chocolatey
      win_command: choco --version
      register: choco_version
      changed_when: false

    - name: Afficher la version de Chocolatey
      debug:
        msg: "Chocolatey installé : {{ choco_version.stdout }}"
