---
- name: Installer Chocolatey sur Windows
  hosts: windows
  vars:
  ansible_user: "{{ lookup('env', WIN_USERNAME }}"
  ansible_password: "{{ lookup('env', WIN_PASSWORD }}"
  tasks:
    - name: Télécharger et installer Chocolatey
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force;
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      args:
        executable: powershell.exe
      register: chocolatey_result
      changed_when: "'Chocolatey installed' in chocolatey_result.stdout"
      
    - name: Vérifier l'installation de Chocolatey
      win_command: choco --version
      register: choco_version
      changed_when: false

    - name: Afficher la version de Chocolatey
      debug:
        msg: "Chocolatey installé : {{ choco_version.stdout }}"
