- name: Deploy VM on vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Debug Variables
      debug:
        msg:
          - "vCenter: {{ lookup('env', 'VCENTER_HOSTNAME') }}"
          - "Cluster: {{ lookup('env', 'CLUSTER_NAME') }}"
          - "Datastore: {{ lookup('env', 'DATASTORE_NAME') }}"
          - "VM Name: {{ lookup('env', 'VM_NAME') }}"
          - "Template: {{ lookup('env', 'VM_TEMPLATE') }}"
          - "Memory MB: {{ lookup('env', 'VM_MEMORY_MB') }}"
          - "Num CPUs: {{ lookup('env', 'VM_NUM_CPUS') }}"

    - name: Create VM from template
      community.vmware.vmware_guest:
        hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') | default('vcenter.example.com') }}"
        username: "{{ lookup('env', 'VCENTER_USERNAME') | default('admin@domain.local') }}"
        password: "{{ lookup('env', 'VCENTER_PASSWORD') | default('password') }}"
        validate_certs: no
        name: "{{ lookup('env', 'VM_NAME') | default('Default_VM') }}"
        template: "{{ lookup('env', 'VM_TEMPLATE') | default('Ubuntu-Template') }}"
        datacenter: "{{ lookup('env', 'DATACENTER_NAME') | default('Datacenter') }}"
        cluster: "{{ lookup('env', 'CLUSTER_NAME') | default('Cluster1') }}"
        datastore: "{{ lookup('env', 'DATASTORE_NAME') | default('Datastore1') }}"
        folder: "/"
        hardware:
          memory_mb: "{{ lookup('env', 'VM_MEMORY_MB') | default(4096) | int }}"
          num_cpus: "{{ lookup('env', 'VM_NUM_CPUS') | default(2) | int }}"
        networks:
          - name: "{{ lookup('env', 'NETWORK_NAME') | default('VM Network') }}"
            type: "dhcp"
        state: poweredon
