- name: Deploy VM on vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VM from template
      community.vmware.vmware_guest:
        hostname: "vcenter.example.com"
        username: "admin@domain.local"
        password: "password"
        validate_certs: no
        name: "New_VM"
        template: "Ubuntu-Template"
        datacenter: "Datacenter"
        cluster: "Cluster1"
        folder: "/VMs"
        hardware:
          memory_mb: 4096
          num_cpus: 2
        networks:
          - name: "VM Network"
            type: "dhcp"
        state: poweredon
