- name: Deploy VM on vCenter
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/vcenter.yml
  tasks:
    - name: Create VM from template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        datacenter: "{{ datacenter_name }}"
        cluster: "{{ cluster_name }}"
        folder: "/VMs"
        hardware:
          memory_mb: "{{ vm_memory_mb }}"
          num_cpus: "{{ vm_num_cpus }}"
        networks:
          - name: "{{ network_name }}"
            type: "dhcp"
        state: poweredon
