- name: Deploy VM on vCenter
  hosts: localhost
  gather_facts: no
  vars:
    vm_memory_mb: "{{ VM_MEMORY_MB | default(4096) | int }}"
    vm_num_cpus: "{{ VM_NUM_CPUS | default(2) | int }}"
    vm_name: "{{ lookup('env', 'VM_NAME') | default('Default_VM') }}"
  tasks:
    - name: Debug Variables (Vérification)
      debug:
        msg:
          - "Memory MB: {{ vm_memory_mb }}"
          - "Num CPUs: {{ vm_num_cpus }}"
          - "VM Name : {{ vm_name}}"

    - name: Create VM from template
      community.vmware.vmware_guest:
        hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') | default('vcenter.example.com') }}"
        username: "{{ lookup('env', 'VCENTER_USERNAME') | default('admin@domain.local') }}"
        password: "{{ lookup('env', 'VCENTER_PASSWORD') | default('password') }}"
        validate_certs: no
        name: "{{ vm_name }}"
        template: "{{ lookup('env', 'VM_TEMPLATE') | default('Ubuntu-Template') }}"
        datacenter: "{{ lookup('env', 'DATACENTER_NAME') | default('Datacenter') }}"
        cluster: "{{ lookup('env', 'CLUSTER_NAME') | default('Cluster1') }}"
        datastore: "{{ lookup('env', 'DATASTORE_NAME') | default('Datastore1') }}"
        guest_id: "{{ lookup('env', 'GUEST_ID') | default('ubuntu64Guest') }}"
        folder: "/"
        hardware:
          memory_mb: "{{ vm_memory_mb }}"
          num_cpus: "{{ vm_num_cpus }}"
        networks:
          - name: "{{ lookup('env', 'NETWORK_NAME') | default('VM Network') }}"
            type: "dhcp"
        state: poweredon
