- name: Send API Requests to ECS
  hosts: localhost
  vars:
    user_name: "{{ USER_NAME | lower }}"
    target_namespace: "{{ TARGET_NAMESPACE | lower }}"
    action: "{{ ACTION | lower }}"  # "create","delete","modify","list"

  tasks:
    - name: Set environment variables
      set_fact:
        target_url: "{{ lookup('env', 'TARGET_URL') }}"
        auth_header: "Basic {{ lookup('env', 'API_KEY') }}"

    - name: Debug environment variables
      debug:
        msg:
          - "Action: {{ action }}"

    - name: Check if API-KEY is set
      fail:
        msg: "API-KEY environment variable is not set."
      when: auth_header == "Basic "

    - name: Disable SSL certificate validation
      set_fact:
        no_ssl_validation: |
          import ssl
          ssl._create_default_https_context = ssl._create_unverified_context

    - name: Get target auth token
      uri:
        url: "{{ target_url }}/login"
        method: GET
        headers:
          Authorization: "{{ auth_header }}"
        validate_certs: no
        timeout: 60
      register: target_response

    - name: Check if target auth token request was successful
      fail:
        msg: "Failed to get target auth token. Status code: {{ target_response.status }}"
      when: target_response.status != 200

    - name: Extract target auth token
      set_fact:
        target_token: "{{ target_response['x_sds_auth_token'] | default('') }}"

    - name: Check if target auth token was extracted
      fail:
        msg: "Target auth token not found in response."
      when: target_token == ''

    - name: Create IAM user
      uri:
        url: "{{ target_url }}/iam?Action=CreateUser&UserName={{ user_name | urlencode }}&Path=/"
        method: POST
        headers:
          Content-Type: "application/xml"
          X-SDS-AUTH-TOKEN: "{{ target_token }}"
          x-emc-namespace: "{{ target_namespace }}"
        validate_certs: no
        return_content: yes
      register: user_response
      when: action == "create"

    - name: Debug user creation response
      debug:
        var: user_response
      when: 
        - action == "create"
        - user_response.status == 200

    - name: Check if user creation was successful
      fail:
        msg: "Failed to create IAM user. Status code: {{ user_response.status }}"
      when: 
        - action == "create"
        - user_response.status != 200

    - name: Create IAM access key
      uri:
        url: "{{ target_url }}/iam?Action=CreateAccessKey&UserName={{ user_name | urlencode }}"
        method: POST
        headers:
          Content-Type: "application/xml"
          X-SDS-AUTH-TOKEN: "{{ target_token }}"
          x-emc-namespace: "{{ target_namespace }}"
        validate_certs: no
        return_content: yes
      register: access_key_response
      when: action == "create"

    - name: Debug access key response
      debug:
        var: access_key_response
      when: 
        - action == "create"
        - access_key_response.status == 200

    - name: Check if access key creation was successful
      fail:
        msg: "Failed to create IAM user access key. Status code: {{ access_key_response.status }}"
      when: 
        - action == "create"
        - access_key_response.status != 200

    - name: Set AccessKey fact
      set_fact:
        AccessKeyId: "{{ access_key_response.content | regex_findall('AccessKeyId>(.*?)<') | select('match', '^[^\\s]+$') | first }}"
        SecretAccessKey: "{{ access_key_response.content | regex_findall('SecretAccessKey>(.*?)<') | select('match', '^[^\\s]+$') | first }}"
      when: 
        - action == "create"
        - access_key_response.status == 200

    - name: Print AccessKey and SecretKey
      debug:
        msg:
          - "AccessKeyId: {{ AccessKeyId }}"
          - "SecretAccessKey: {{ SecretAccessKey }}"
      when: 
        - action == "create"
        - access_key_response.status == 200

    - name: List IAM user policies
      uri:
        url: "{{ target_url }}/iam?Action=ListAttachedUserPolicies&UserName={{ user_name | urlencode }}"
        method: POST
        headers:
          Content-Type: "application/xml"
          X-SDS-AUTH-TOKEN: "{{ target_token }}"
          x-emc-namespace: "{{ target_namespace }}"
        validate_certs: no
        return_content: yes
      register: user_policy_response
      when: action == "delete"

    - name: Set policy ARNs fact
      set_fact:
        policy_arns: "{{ user_policy_response.content | regex_findall('PolicyArn>(.*?)<') | select('match', '^[^\\s]+$') }}"
      when: action == "delete"

    - name: Detach IAM user policies
      uri:
        url: "{{ target_url }}/iam?Action=DetachUserPolicy&UserName={{ user_name | urlencode }}&PolicyArn={{ item | urlencode }}"
        method: POST
        headers:
          Content-Type: "application/xml"
          X-SDS-AUTH-TOKEN: "{{ target_token }}"
          x-emc-namespace: "{{ target_namespace }}"
        validate_certs: no
        return_content: yes
      register: detach_policy_response
      loop: "{{ policy_arns }}"
      when: action == "delete"

    - name: List IAM user access keys
      uri:
        url: "{{ target_url }}/iam?Action=ListAccessKeys&UserName={{ user_name | urlencode }}"
        method: POST
        headers:
          Content-Type: "application/xml"
          X-SDS-AUTH-TOKEN: "{{ target_token }}"
          x-emc-namespace: "{{ target_namespace }}"
        validate_certs: no
        return_content: yes
      register: access_keys_response
      when: action == "delete"

    - name: Set access key IDs fact
      set_fact:
        access_key_ids: "{{ access_keys_response.content | regex_findall('AccessKeyId>(.*?)<') | select('match', '^[A-Z0-9]+$') }}"
      when: action == "delete"

    - name: Delete IAM user access keys
      uri:
        url: "{{ target_url }}/iam?Action=DeleteAccessKey&UserName={{ user_name | urlencode }}&AccessKeyId={{ item | urlencode }}"
        method: POST
        headers:
          Content-Type: "application/xml"
          X-SDS-AUTH-TOKEN: "{{ target_token }}"
          x-emc-namespace: "{{ target_namespace }}"
        validate_certs: no
        return_content: yes
      register: delete_access_key_response
      loop: "{{ access_key_ids }}"
      when: action == "delete"

    - name: Delete IAM user
      uri:
        url: "{{ target_url }}/iam?Action=DeleteUser&UserName={{ user_name | urlencode }}&Path=/"
        method: POST
        headers:
          Content-Type: "application/xml"
          X-SDS-AUTH-TOKEN: "{{ target_token }}"
          x-emc-namespace: "{{ target_namespace }}"
        validate_certs: no
        return_content: yes
      register: delete_user_response
      when: action == "delete"

    - name: List all IAM users
      uri:
        url: "{{ target_url }}/iam?Action=ListUsers"
        method: POST
        headers:
          Content-Type: "application/xml"
          X-SDS-AUTH-TOKEN: "{{ target_token }}"
          x-emc-namespace: "{{ target_namespace }}"
        validate_certs: no
        return_content: yes
      register: list_users_response
      when: action == "list"

    - name: Debug list users response
      debug:
        var: list_users_response
      when: action == "list"

    - name: Set user names fact
      set_fact:
        user_names: "{{ list_users_response.content | regex_findall('UserName>(.*?)<') | select('match', '^[^\\s]+$') }}"
      when: action == "list"

    - name: List access keys for each user
      uri:
        url: "{{ target_url }}/iam?Action=ListAccessKeys&UserName={{ user_name_item | urlencode }}"
        method: POST
        headers:
          Content-Type: "application/xml"
          X-SDS-AUTH-TOKEN: "{{ target_token }}"
          x-emc-namespace: "{{ target_namespace }}"
        validate_certs: no
        return_content: yes
      register: user_access_keys_response
      loop: "{{ user_names }}"
      loop_control:
        loop_var: user_name_item
      when: action == "list"

    - name: Set access keys fact for each user
      set_fact:
        user_access_keys: "{{ user_access_keys | default({}) | combine({user_name_item: (user_access_keys_response.content | regex_findall('AccessKeyId>(.*?)<')) | default([])}) }}"
      loop: "{{ user_names }}"
      loop_control:
        loop_var: user_name_item
      when: action == "list"

    - name: Debug user access keys response
      debug:
        msg: "User: {{ item }}, Access Keys: {{ user_access_keys[item] }}"
      loop: "{{ user_names }}"
      loop_control:
        loop_var: item
      when: action == "list"
