- name: Deploy VM on vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VM from template
      community.vmware.vmware_guest:
        hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
        username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
        password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
        validate_certs: no
        name: "{{ lookup('env', 'VM_NAME') }}"
        template: "{{ lookup('env', 'VM_TEMPLATE') }}"
        datacenter: "{{ lookup('env', 'DATASTORE_NAME') }}"
        cluster: "{{ lookup('env', 'CLUSTER_NAME') }}"
        folder: "/VMs"
        hardware:
          memory_mb: "{{ lookup('env', 'VM_MEMORY_MB') }}"
          num_cpus: "{{ lookup('env', 'VM_NUM_CPUS') }}"
        networks:
          - name: "{{ lookup('env', 'NETWORK_NAME') }}"
            type: "dhcp"
        state: poweredon
