- name: Liste des VMs sur vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Récupérer la liste des VMs
      community.vmware.vmware_vm_info:
        hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
        username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
        password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
        validate_certs: no
      register: vm_list

    - name: Vérifier si des VMs sont présentes
      fail:
        msg: "Aucune VM trouvée sur vCenter."
      when: vm_list.virtual_machines is not defined or vm_list.virtual_machines | length == 0

    - name: Filtrer et structurer les infos des VMs
      set_fact:
        vm_info: "{{ vm_list.virtual_machines | map(attribute='guest_name') | list }}"

    - name: Retourner les VMs en JSON (format API)
      debug:
        msg: "{{ vm_info | to_json }}"
