- name: Liste des VMs sur vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Récupérer la liste des VMs
      community.vmware.vmware_vm_info:
        hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
        username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
        password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
        validate_certs: no
      register: vm_list

    - name: Afficher la liste des VMs
      debug:
        msg: "{{ vm_list.virtual_machines | map(attribute='name') | list }}"
